BEGIN;

CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(120) NOT NULL,
    endereco VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS doador (
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_doador_usuario
        FOREIGN KEY (id) REFERENCES usuario(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS beneficiario (
    id BIGINT PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL,
    nivel_prioridade SMALLINT NOT NULL,
    CONSTRAINT fk_beneficiario_usuario
        FOREIGN KEY (id) REFERENCES usuario(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_beneficiario_tipo
        CHECK (tipo IN ('FAMILIA', 'ONG', 'ESCOLA', 'ABRIGO', 'COMUNIDADE')),
    CONSTRAINT chk_beneficiario_prioridade
        CHECK (nivel_prioridade BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS item_doacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doador_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    categoria VARCHAR(30) NOT NULL,
    descricao TEXT NOT NULL,
    quantidade INTEGER NOT NULL,
    estado_conservacao VARCHAR(20) NOT NULL,
    data_cadastro DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'DISPONIVEL',
    CONSTRAINT fk_item_doacao_doador
        FOREIGN KEY (doador_id) REFERENCES doador(id),
    CONSTRAINT chk_item_doacao_categoria
        CHECK (
            categoria IN (
                'ALIMENTO_NAO_PERECIVEL',
                'ROUPA',
                'MATERIAL_ESCOLAR',
                'MOVEL',
                'HIGIENE',
                'OUTROS'
            )
        ),
    CONSTRAINT chk_item_doacao_quantidade
        CHECK (quantidade > 0),
    CONSTRAINT chk_item_doacao_estado
        CHECK (estado_conservacao IN ('NOVO', 'BOM', 'USADO', 'PRECISA_REPARO')),
    CONSTRAINT chk_item_doacao_status
        CHECK (status IN ('DISPONIVEL', 'RESERVADO', 'ENTREGUE', 'CANCELADO'))
);

CREATE TABLE IF NOT EXISTS solicitacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beneficiario_id BIGINT NOT NULL,
    item_doacao_id BIGINT NOT NULL,
    quantidade_solicitada INTEGER NOT NULL,
    justificativa TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    CONSTRAINT fk_solicitacao_beneficiario
        FOREIGN KEY (beneficiario_id) REFERENCES beneficiario(id),
    CONSTRAINT fk_solicitacao_item_doacao
        FOREIGN KEY (item_doacao_id) REFERENCES item_doacao(id),
    CONSTRAINT chk_solicitacao_quantidade
        CHECK (quantidade_solicitada > 0),
    CONSTRAINT chk_solicitacao_status
        CHECK (status IN ('PENDENTE', 'APROVADA', 'REJEITADA', 'CONCLUIDA'))
);

CREATE TABLE IF NOT EXISTS doacao_efetivada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_doacao_id BIGINT NOT NULL,
    doador_id BIGINT NOT NULL,
    beneficiario_id BIGINT NOT NULL,
    data DATE NOT NULL,
    observacoes TEXT,
    CONSTRAINT fk_doacao_efetivada_item
        FOREIGN KEY (item_doacao_id) REFERENCES item_doacao(id),
    CONSTRAINT fk_doacao_efetivada_doador
        FOREIGN KEY (doador_id) REFERENCES doador(id),
    CONSTRAINT fk_doacao_efetivada_beneficiario
        FOREIGN KEY (beneficiario_id) REFERENCES beneficiario(id)
);

CREATE INDEX IF NOT EXISTS idx_item_doacao_doador_id
    ON item_doacao(doador_id);

CREATE INDEX IF NOT EXISTS idx_solicitacao_beneficiario_id
    ON solicitacao(beneficiario_id);

CREATE INDEX IF NOT EXISTS idx_solicitacao_item_doacao_id
    ON solicitacao(item_doacao_id);

CREATE INDEX IF NOT EXISTS idx_doacao_efetivada_item_doacao_id
    ON doacao_efetivada(item_doacao_id);

CREATE INDEX IF NOT EXISTS idx_doacao_efetivada_doador_id
    ON doacao_efetivada(doador_id);

CREATE INDEX IF NOT EXISTS idx_doacao_efetivada_beneficiario_id
    ON doacao_efetivada(beneficiario_id);

COMMIT;
